[package]
name = "invite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.5"
crossterm = "0.27.0"
json = "0.12.4"
tui = "0.19.0"

[workspace]
members = [
    ".",
    "./src/util"
]
